### ISSUE TITLE
Payment Failure.

### ISSUE THREAD

**Issue by primoashbee** [PayMaya/PayMaya-PHP-SDK#11]
I used your sample Checkout.php.
Tried all the Test Cards for checking out.

![image](https://user-images.githubusercontent.com/11629214/35469831-ad288d00-0378-11e8-9019-dd1f5eb4bea3.png)

Same results.
I dont know if this is because im using sandbox or not.

**Comment by diwadm** [comment]
We've updated the test credit cards and sandbox API keys. Please use the updated ones in this page:

https://developers.paymaya.com/blog/entry/api-test-merchants-and-test-cards
