### ISSUE TITLE
Checkout returning code PY0001

### ISSUE THREAD

**Issue by aceraven777** [PayMaya/PayMaya-PHP-SDK#14]
When I try to do a checkout, its returning:

```
array:2 [▼
  "code" => "PY0001"
  "message" => "A problem is encountered. Please contact your system administrator."
]
```

It was working last time. I tried all of the API keys here: https://developers.paymaya.com/blog/entry/checkout-api-test-credit-card-account-numbers

But none of  them works.

**Comment by aceraven777** [comment]
Any update on this?

**Comment by akosibentoy** [comment]
Any update on this?

**Comment by aceraven777** [comment]
Hi @akosibentoy ,

I tested this again and it's working now. Can you share your code here?

And what API keys are you using?

I'm using:
```
PUBLIC_API_KEY=pk-lNAUk1jk7VPnf7koOT1uoGJoZJjmAxrbjpj6urB8EIA
SECRET_API_KEY=sk-fzukI3GXrzNIUyvXY3n16cji8VTJITfzylz5o5QzZMC
```

**Comment by iamkenken** [comment]
@aceraven777 using that keys, mine is working now.

**Comment by poldiwa** [comment]
> Hi @akosibentoy ,
> 
> I tested this again and it's working now. Can you share your code here?
> 
> And what API keys are you using?
> 
> I'm using:
> 
> ```
> PUBLIC_API_KEY=pk-lNAUk1jk7VPnf7koOT1uoGJoZJjmAxrbjpj6urB8EIA
> SECRET_API_KEY=sk-fzukI3GXrzNIUyvXY3n16cji8VTJITfzylz5o5QzZMC
> ```

how did you got these keys?

**Comment by aceraven777** [comment]
We got it from the PayMaya site.

API Test Merchants and Test Cards: https://developers.paymaya.com/blog/entry/api-test-merchants-and-test-cards

**Comment by aceraven777** [comment]
@poldiwa

We got it from the PayMaya site.

API Test Merchants and Test Cards: https://developers.paymaya.com/blog/entry/api-test-merchants-and-test-cards

**Comment by poldiwa** [comment]
@aceraven777 thanks for the quick response, everything is working now. 

 if ever someone on the team can read this. the link on https://developers.paymaya.com/blog/entry/paymaya-checkout-faq#Keys is outdated
