### ISSUE TITLE
Invalid authentication credentials

### ISSUE THREAD

**Issue by aceraven777** [PayMaya/PayMaya-PHP-SDK#26]
I developed a library in Laravel: https://github.com/aceraven777/laravel-paymaya

This library was based on this SDK library.

I have a user here that raised an issue: https://github.com/aceraven777/laravel-paymaya/issues/15

He said that the sandbox credentials are working, but the production credentials don't work, can someone help me investigate this issue?

**Comment by rjarce** [comment]
Most likely the keys are incorrect. Probably the sandbox keys were loaded and used when the user switched to Production?

If the user is unable to make it work, he/she can raise it to their account manager or our fulfillment team to check.

**Comment by hubertursua** [comment]
I would also suggest you import the PayMaya SDK as a composer dependency instead of copy-pasting. This will ensure anyone who installs your library will get the latest version of the PayMaya SDK as well.
