### ISSUE TITLE
psr/log version depedency locked only on 1.0.0

### ISSUE THREAD

**Issue by jomaf1010** [PayMaya/PayMaya-PHP-SDK#6]
Request: 

#### psr/log : 1.0.0  - psr/log : ~1.0

It would be nice you can adjust psr/log dependency to support version > 1.0, 
at least to update composer.json to require ~1.0.

I encountered this dependency version conflict on laravel5.4 as all module requires ~1.0. (1.0.2 specifically) and the sdk is trying to install 1.0.0 version.

``` lua
 Problem 1
    - Can only install one of: psr/log[1.0.0, 1.0.2]. <-- trying to install two version 
    - Can only install one of: psr/log[1.0.2, 1.0.0].
    - Can only install one of: psr/log[1.0.0, 1.0.2].
    - paymaya/paymaya-sdk 0.0.1 requires psr/log 1.0.0 -> satisfiable by psr/log[1.0.0].
    - Installation request for paymaya/paymaya-sdk * -> satisfiable by paymaya/paymaya-sdk[0.0.1].
    - Installation request for psr/log (locked at 1.0.2, required as ^1.0) -> satisfiable by psr/log[1.0.2].
```

**Comment by diwadm** [comment]
@jomaf1010 Thank you for the suggestion. We'll do this.

**Comment by rjarce** [comment]
Closing with PR #24
