### ISSUE TITLE
Undefined index: ID in Register WEBHOOK

### ISSUE THREAD

**Issue by aanthraxx** [PayMaya/PayMaya-PHP-SDK#8]
`$successWebhook = new Webhook();`
`$successWebhook->id = $itemCheckout->id;`
`$successWebhook->name = Webhook::CHECKOUT_SUCCESS;`
`$successWebhook->callbackUrl = "http://localhost:8000/paymaya/success";`
`$successWebhook->register();`

i was getting this error, I'm using Symfony Framework 3.3

`Undefined index: ID`

even though I already set the ID returned by PayMaya Checkout.

**Comment by diwadm** [comment]
That behavior happens if the call to the Checkout API fails.

**Comment by rmrhz** [comment]
@diwadm it should be throwing an exception instead of returning `Undefined index: ID`. That's bad implementation.
